# Generated by Django 2.2.7 on 2019-12-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='brief_description',
            field=models.CharField(default='Some organization', max_length=150),
        ),
        migrations.AddField(
            model_name='organization',
            name='location',
            field=models.CharField(default='St. Petersburg', max_length=40),
        ),
    ]
