# Generated by Django 2.2.7 on 2019-12-01 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20191201_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('start', models.CharField(max_length=5)),
                ('end', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('middlename', models.CharField(max_length=20)),
                ('date_of_birth', models.CharField(max_length=10)),
                ('post', models.CharField(max_length=20)),
                ('hours_per_week', models.IntegerField()),
                ('days', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.Dates')),
            ],
        ),
    ]
