# Generated by Django 2.2.7 on 2019-12-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_dates_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='days',
        ),
        migrations.AddField(
            model_name='person',
            name='days',
            field=models.ManyToManyField(to='organizations.Dates'),
        ),
    ]
