# Generated by Django 2.2.7 on 2019-12-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_auto_20191203_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='days',
        ),
        migrations.AddField(
            model_name='person',
            name='days',
            field=models.ManyToManyField(to='organizations.Dates'),
        ),
    ]
