# Generated by Django 2.2.7 on 2019-12-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_auto_20191203_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='person',
            field=models.ManyToManyField(to='organizations.Person'),
        ),
    ]
