# Generated by Django 2.2.7 on 2019-12-06 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
